/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.vistas;

/**
 *
 * @author clara
 */
public class VistaTiposHabitaciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaTiposHabitaciones
     */
    public VistaTiposHabitaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textTitleHabitaciones = new javax.swing.JLabel();
        textTipoHabitacionDni = new javax.swing.JLabel();
        textTipoHabitacionNombre = new javax.swing.JLabel();
        textTipoHabitacionPrecio = new javax.swing.JLabel();
        tipoHabitacionGuardar = new javax.swing.JButton();
        tipoHabitacionEditar = new javax.swing.JButton();
        tipoHabitacionLimpiar = new javax.swing.JButton();
        tipoHabitacionEliminar = new javax.swing.JButton();
        textTipoHabitacionPersonas = new javax.swing.JLabel();
        tipoHabitacionNombre = new javax.swing.JTextField();
        tipoHabitacionPersonas = new javax.swing.JComboBox<>();
        tipoHabitacionPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tipoHabitacionId = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        textTitleHabitaciones.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        textTitleHabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/hierarchical-structure.png"))); // NOI18N
        textTitleHabitaciones.setText("TIPOS DE HABITACIONES");

        textTipoHabitacionDni.setText("ID ");

        textTipoHabitacionNombre.setText("NOMBRE TIPO");

        textTipoHabitacionPrecio.setText("PRECIO POR NOCHE");

        tipoHabitacionGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/checked-1.png"))); // NOI18N
        tipoHabitacionGuardar.setText("GUARDAR");

        tipoHabitacionEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/pencil.png"))); // NOI18N
        tipoHabitacionEditar.setText("EDITAR");

        tipoHabitacionLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/escoba.png"))); // NOI18N
        tipoHabitacionLimpiar.setText("LIMPIAR");

        tipoHabitacionEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/cancel.png"))); // NOI18N
        tipoHabitacionEliminar.setText("ELIMINAR");

        textTipoHabitacionPersonas.setText("CAPACIDAD  MAX");

        tipoHabitacionNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoHabitacionNombreActionPerformed(evt);
            }
        });

        tipoHabitacionPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jLabel7.setText("Persona/s");

        tipoHabitacionId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo ", "2", "3", "4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textTipoHabitacionDni, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoHabitacionGuardar)
                            .addComponent(textTipoHabitacionNombre)
                            .addComponent(textTipoHabitacionPersonas)
                            .addComponent(textTipoHabitacionPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tipoHabitacionPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tipoHabitacionNombre)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tipoHabitacionEditar)
                                    .addGap(93, 93, 93)
                                    .addComponent(tipoHabitacionLimpiar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                                    .addComponent(tipoHabitacionEliminar))
                                .addComponent(tipoHabitacionPrecio)
                                .addComponent(tipoHabitacionId, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(textTitleHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(textTitleHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTipoHabitacionDni)
                    .addComponent(tipoHabitacionId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTipoHabitacionNombre)
                    .addComponent(tipoHabitacionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTipoHabitacionPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoHabitacionPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTipoHabitacionPrecio)
                    .addComponent(tipoHabitacionPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoHabitacionGuardar)
                    .addComponent(tipoHabitacionEditar)
                    .addComponent(tipoHabitacionLimpiar)
                    .addComponent(tipoHabitacionEliminar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoHabitacionNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoHabitacionNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoHabitacionNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel textTipoHabitacionDni;
    private javax.swing.JLabel textTipoHabitacionNombre;
    private javax.swing.JLabel textTipoHabitacionPersonas;
    private javax.swing.JLabel textTipoHabitacionPrecio;
    private javax.swing.JLabel textTitleHabitaciones;
    private javax.swing.JButton tipoHabitacionEditar;
    private javax.swing.JButton tipoHabitacionEliminar;
    private javax.swing.JButton tipoHabitacionGuardar;
    private javax.swing.JComboBox<String> tipoHabitacionId;
    private javax.swing.JButton tipoHabitacionLimpiar;
    private javax.swing.JTextField tipoHabitacionNombre;
    private javax.swing.JComboBox<String> tipoHabitacionPersonas;
    private javax.swing.JTextField tipoHabitacionPrecio;
    // End of variables declaration//GEN-END:variables
}
