/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.vistas;

import hotel.modelo.Huesped;
import hotel.modelo.HuespedData;
import hotel.modelo.Conexion;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author clara
 */
public class VistaHuesped extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaHuesped
     */
    private Conexion conexion;
    private HuespedData huespedData;

    public VistaHuesped() {
        initComponents();

        try {
            conexion = new Conexion();
            huespedData = new HuespedData(conexion);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaHuesped.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textTitleHuesped = new javax.swing.JLabel();
        textHuespedDni = new javax.swing.JLabel();
        textHuespedNombre = new javax.swing.JLabel();
        textHuespedDomicilio = new javax.swing.JLabel();
        textHuespedEmail = new javax.swing.JLabel();
        textHuespedCelular = new javax.swing.JLabel();
        JThuespedDni = new javax.swing.JTextField();
        JThuespedNombre = new javax.swing.JTextField();
        JThuespedDomicilio = new javax.swing.JTextField();
        JThuespedEmail = new javax.swing.JTextField();
        JThuespedCelular = new javax.swing.JTextField();
        huespedBuscar = new javax.swing.JButton();
        huespedGuardar = new javax.swing.JButton();
        huespedBorrar = new javax.swing.JButton();
        huespedEditar = new javax.swing.JButton();
        huespedLimpiar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        textTitleHuesped.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        textTitleHuesped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/user-49.png"))); // NOI18N
        textTitleHuesped.setText(" DATOS HUESPED");

        textHuespedDni.setText("DNI");

        textHuespedNombre.setText("NOMBRE");

        textHuespedDomicilio.setText("DOMICILIO");

        textHuespedEmail.setText("E-MAIL");

        textHuespedCelular.setText("CELULAR");

        JThuespedNombre.setToolTipText("");

        JThuespedDomicilio.setToolTipText("");

        JThuespedEmail.setToolTipText("");

        huespedBuscar.setText("BUSCAR");
        huespedBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huespedBuscarActionPerformed(evt);
            }
        });

        huespedGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/checked-1.png"))); // NOI18N
        huespedGuardar.setText("GUARDAR");
        huespedGuardar.setToolTipText("");
        huespedGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huespedGuardarActionPerformed(evt);
            }
        });

        huespedBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/cancel.png"))); // NOI18N
        huespedBorrar.setText("BORRAR");
        huespedBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huespedBorrarActionPerformed(evt);
            }
        });

        huespedEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/pencil.png"))); // NOI18N
        huespedEditar.setText("EDITAR");
        huespedEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huespedEditarActionPerformed(evt);
            }
        });

        huespedLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/escoba.png"))); // NOI18N
        huespedLimpiar.setText("LIMPIAR");
        huespedLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huespedLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textHuespedDni, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textHuespedNombre)
                            .addComponent(textHuespedDomicilio)
                            .addComponent(textHuespedEmail)
                            .addComponent(textHuespedCelular))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(huespedGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(huespedEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(huespedLimpiar)
                                .addGap(26, 26, 26)
                                .addComponent(huespedBorrar))
                            .addComponent(JThuespedNombre)
                            .addComponent(JThuespedDomicilio)
                            .addComponent(JThuespedEmail)
                            .addComponent(JThuespedCelular)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JThuespedDni, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(huespedBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(textTitleHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(textHuespedDni))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(textTitleHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JThuespedDni, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(huespedBuscar))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JThuespedNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textHuespedNombre))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textHuespedDomicilio)
                    .addComponent(JThuespedDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textHuespedEmail)
                    .addComponent(JThuespedEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JThuespedCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textHuespedCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(huespedBorrar)
                    .addComponent(huespedGuardar)
                    .addComponent(huespedLimpiar)
                    .addComponent(huespedEditar))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void huespedGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huespedGuardarActionPerformed
       // Guarda  un huesped nuevo


        int huespedDni=Integer.parseInt (JThuespedDni.getText());
        String huespedNombre=JThuespedNombre.getText();
        String huespedDomicilio=JThuespedDomicilio.getText();
        String huespedEmail=JThuespedEmail.getText();
        String huespedCelular=JThuespedCelular.getText();
        
        Huesped huesped=new Huesped(huespedDni, huespedNombre, huespedDomicilio, huespedEmail, huespedCelular);
        huespedData.guardarHuesped(huesped);
        
      JOptionPane.showMessageDialog(huespedGuardar, "Nuevo huesped agregado ");
        
    }//GEN-LAST:event_huespedGuardarActionPerformed

    private void huespedBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huespedBuscarActionPerformed
 
        // Búsca un huesped por DNI

        int buscarHuespedDni = Integer.parseInt(JThuespedDni.getText());
        Huesped huesped = huespedData.buscarHuesped(buscarHuespedDni);
        
        if(huesped != null){
            JThuespedNombre.setText(huesped.getHuespedNombre());
            JThuespedDomicilio.setText(huesped.getHuespedDomicilio());
            JThuespedEmail.setText(huesped.getHuespedEmail());
            JThuespedCelular.setText(huesped.getHuespedCelular());

        } else{
            JOptionPane.showMessageDialog(huespedBuscar, "El DNI no existe, o ha introducido caracteres no válidos. Solo ingrese números. ");
        }

    }//GEN-LAST:event_huespedBuscarActionPerformed

    private void huespedBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huespedBorrarActionPerformed
       int huespedDni=Integer.parseInt(JThuespedDni.getText());
       huespedData.borrarHuesped(huespedDni);
       
        JOptionPane.showMessageDialog(huespedBorrar, "Huesped borrado");
    }//GEN-LAST:event_huespedBorrarActionPerformed

    private void huespedEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huespedEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_huespedEditarActionPerformed

    private void huespedLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huespedLimpiarActionPerformed
    JThuespedDni.setText("");
    JThuespedNombre.setText("");
    JThuespedDomicilio.setText("");
    JThuespedEmail.setText("");
     JThuespedCelular.setText("");
    }//GEN-LAST:event_huespedLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JThuespedCelular;
    private javax.swing.JTextField JThuespedDni;
    private javax.swing.JTextField JThuespedDomicilio;
    private javax.swing.JTextField JThuespedEmail;
    private javax.swing.JTextField JThuespedNombre;
    private javax.swing.JButton huespedBorrar;
    private javax.swing.JButton huespedBuscar;
    private javax.swing.JButton huespedEditar;
    private javax.swing.JButton huespedGuardar;
    private javax.swing.JButton huespedLimpiar;
    private javax.swing.JLabel textHuespedCelular;
    private javax.swing.JLabel textHuespedDni;
    private javax.swing.JLabel textHuespedDomicilio;
    private javax.swing.JLabel textHuespedEmail;
    private javax.swing.JLabel textHuespedNombre;
    private javax.swing.JLabel textTitleHuesped;
    // End of variables declaration//GEN-END:variables
}
